### ISSUE TITLE
http://googlevisualr.heroku.com/ is not working

### ISSUE THREAD

**Issue by Shekharrajak** [winston/google_visualr#108]
I am working on plotting system for the ruby gem [Daru](https://github.com/SciRuby/daru) . I want to use google_visualr to plot interactive graphs like[ google chart JS code](https://developers.google.com/chart/?csw=1). 

I read this line in the readme file : 

> Please refer to the GoogleVisualr API Reference site for a complete list of Google charts that you can create with GoogleVisualr.

But I the [link](http://googlevisualr.heroku.com/) is not working any more. Please tell me an alternate source to read more about this gem , so that I can use it in Daru gem. I am trying to understand this gem using spec. 

Can we do all the things like [Google chart tool](https://developers.google.com/chart/?csw=1) ? Is it just a wrapper for Ruby ? 

Ping @winston

**Comment by winston** [comment]
Hi, the link needs an update. Should be http://googlevisualr.herokuapp.com/ instead.

Yes, it's a wrapper around Google Chart. But not for everything. Let me know if the reference site helps to explain more? Thanks!

**Comment by winston** [comment]
Fixed with https://github.com/winston/google_visualr/commit/239caab0baa355588282b2f527d5abc43580aa88
