### ISSUE TITLE
How to draw a table

### ISSUE THREAD

**Issue by Shekharrajak** [winston/google_visualr#112]
I want to do something like this in my rails app : https://jsfiddle.net/wmqogfsu/

**Comment by Shekharrajak** [comment]
Ping @winston , I see there is `to_js` method in data_table.rb but it is just generated the `var data_table = ...` for charts js code.

**Comment by winston** [comment]
Hi, please take a look at the examples in http://googlevisualr.herokuapp.com/. Thanks.

**Comment by Shekharrajak** [comment]
@winston , I saw that we can't draw table similar to charts using the gem. Since it is for only charts and for data table [`#to_js`](https://github.com/winston/google_visualr/blob/master/lib/google_visualr/data_table.rb#L203) method is  for only generating `var data_table = new google.visualization.DataTable(.. ` not the js code inside the script tag . 

Also `render_chart` is not for chart. 

I edited some code and generated the script file.
few lines that I added : 

```
   def to_js_web(element_id='random_id')
      js =  ""
      js << "\n<script type='text/javascript'>"
      js << load_js(element_id)
      js << draw_js(element_id)
      js << "\n</script>"
      js
    end

    def chart_function_name(element_id)
      "draw_#{element_id.gsub('-', '_')}"
    end

    def load_js(element_id)
      language_opt = ", language: '#{language}'" if language

      # "\n    google.charts.load('current', {packages: ['table']});"
      "\n  google.load('visualization', '#{version}', {packages: ['#{package_name}']#{language_opt}, callback: #{chart_function_name(element_id)}});"
    end


    def draw_js(element_id)
      js = ""
      js << "\n  function #{chart_function_name(element_id)}() {"
      js << "\n    #{self.to_js}"
      js << "\n    var table = new google.visualization.Table("
      js << "\n    document.getElementById('#{element_id}'));"
      js << "\n    table.draw(data_table, #{js_parameters(@options)});"
      js << "\n  };"
      js
    end

```

and added a new method `render_table` similarly for the chart. and It works.

**Comment by winston** [comment]
http://googlevisualr.herokuapp.com/docs

Hmm this page should show you how to generate tables. Does that work?

**Comment by Shekharrajak** [comment]
Thanks for sharing this link. I didn't use ` GoogleVisualr::Interactive::Table.new(..)`

but it is not working since it is taking `packages: ['tabletable']` but package must be `table`.

**Comment by winston** [comment]
Hmm something wrong with the code then. But googlevisualr should be based on the latest version of the gem, so it should be correct.

**Comment by Shekharrajak** [comment]
Yes, I am using the forked repo in rails app.
