### ISSUE TITLE
Puma caught this error: undefined method `helper_method' for ActionController::API:Class (NoMethodError)

### ISSUE THREAD

**Issue by Shekharrajak** [winston/google_visualr#117]
When I run `rails s` I see these error

<img width="1256" alt="screen shot 2017-08-03 at 9 53 25 pm" src="https://user-images.githubusercontent.com/5774448/28932184-3b444462-7896-11e7-85c6-95616ae02ff7.png">

but it works fine when I refresh it once. Why always I see these error first time in rails app ?

**Comment by Shekharrajak** [comment]
@winston is there any way to disable the app/helpers/view_helper.rb file, since I do not want to use it.

**Comment by Shekharrajak** [comment]
Fixed via https://github.com/winston/google_visualr/commit/5dd3ffbb470da1d66f34826089a8ce62deffefa6

It will be fixed in newer version.

**Comment by mikecmpbll** [comment]
can we release a new version for this fix? 🚢
