### ISSUE TITLE
Multiple Vertical Axes (logarithmic) on a line chart

### ISSUE THREAD

**Issue by bruparel** [winston/google_visualr#14]
Hello Winston,
Great library, I like it a lot.  One thing that I am trying to do is a line chart with two vertical axes.  The left side axis is volume and varies from hundreds of thousands to may be hundreds or tens, further, it has to be logarithmic scale.  The second vertical axis should be on the right hand side and will display units using again logarithmic scale which can go up to one thousand.  I am trying to use the google Visualization API as a guide, but the vertical axis labels are not displaying and the scale turns plain instead of logarithmic.  Note that if I have just one vertical axis, i.e., the left axis, then the logarithmic scale works fine.

Can you provide some guidance here?

Thanks again.

Bharat

**Comment by santoshkumar611** [comment]
if we need three verticla Axes , what is alignment of vAxes
