### ISSUE TITLE
Drawing charts with AJAX calls

### ISSUE THREAD

**Issue by alienware** [winston/google_visualr#63]
Hi.

I read up previous issues with rendering charts with AJAX requests. I tried a small hard-coded change and I could get the re-drawing of charts with AJAX calls. I followed a suggestion on SO as put down here http://stackoverflow.com/a/10659721.

So, as I said I tried a hard-coded script to draw graphs, where I replaced 
google.setOnLoadCallback(drawChart);
with
google.setOnLoadCallback(drawChart());

and my charts started rendering on AJAX calls, but they don't on HTML request (google.visualization is undefined).

I cannot pinpoint the issue and the reasons behind what is happening because I am not familiar with these setOnLoadCallback and other methods. Would like some comments from you on this and what can I do to include this in render_chart.

This is what I tried to reload my charts:

google.load('visualization','1', {packages: ['corechart']});
google.setOnLoadCallback(draw_chart());
function draw_chart() {
    var data_table = new google.visualization.DataTable();data_table.addColumn({"type":"string","label":"Year"});data_table.addColumn({"type":"number","label":"Sales"});data_table.addColumn({"type":"number","label":"Expenses"});data_table.addRow([{v: "2004"}, {v: 1000}, {v: 400}]);data_table.addRow([{v: "2005"}, {v: 1170}, {v: 460}]);data_table.addRow([{v: "2006"}, {v: 660}, {v: 1120}]);data_table.addRow([{v: "2007"}, {v: 1030}, {v: 540}]);
    var chart = new google.visualization.BarChart(document.getElementById('chart'));
    chart.draw(data_table, {width: 400, height: 240, title: "App Performance", vAxis: {title: "Year", titleTextStyle: {color: "red"}}});
};

**Comment by ror-infobeans** [comment]
Writing `draw_chart()` solved my problem. Thanks @winston !
