### ISSUE TITLE
Control the specific colors for the bars.

### ISSUE THREAD

**Issue by wbasmayor** [winston/google_visualr#80]
Perhaps this feature can be added someday with the next version? I currently there is no way to mimic this behavior for visualr.

```
 // from https://developers.google.com/chart/interactive/docs/gallery/columnchart#Colors
  var data = google.visualization.arrayToDataTable([
     ['Element', 'Density', { role: 'style' }],
     ['Copper', 8.94, '#b87333'],            // RGB value
     ['Silver', 10.49, 'silver'],            // English color name
     ['Gold', 19.30, 'gold'],

   ['Platinum', 21.45, 'color: #e5e4e2' ], // CSS-style declaration
  ]);
```

**Comment by iamarmanjon** [comment]
is this closed? I can't seem to change the colors of my bars.

data_table.new_column('string', 'category')
data_table.new_column('number', 'value')

data_table.add_rows(['Fit', 3000])
data_table.add_rows(['Unfit', 320])

Where will I add to change column chart colors?

**Comment by winston** [comment]
@iamarmanjon Do you mind showing your code here? Thanks.

**Comment by iamarmanjon** [comment]
Hi Winston,

We already fixed it, didn't know that set_column method has 5 params,
didn't know that there was an ID.

**Comment by winston** [comment]
Great! :)
