### ISSUE TITLE
Add support material design for Bar charts and Column Chart

### ISSUE THREAD

**Issue by ermolaev** [winston/google_visualr#85]
Example https://google-developers.appspot.com/chart/interactive/docs/gallery/barchart#Material

Thanks.

**Comment by egoens** [comment]
I have a PR in for addressing the material charts https://github.com/winston/google_visualr/pull/88. Perhaps you can fork instead and use this solution if it does not get merged in.

**Comment by winston** [comment]
@ermolaev Added in #95 and pushed as version 2.5.0. :bow:
