### ISSUE TITLE
Support to add packages

### ISSUE THREAD

**Issue by dtelaroli** [winston/google_visualr#86]
I need to create a detailed chart to the select event.

Eg.:
```
chart = GoogleVisualr::Interactive::ColumnChart.new
chart.add_package('table')
```

**Comment by winston** [comment]
@dtelaroli Can you elaborate a bit more. Not sure if I understand what you mean by `package`?

**Comment by dtelaroli** [comment]
@winston each chart contains one google visualization package, for exemple:
ColumnChart include de corechart (https://github.com/winston/google_visualr/blob/master/lib/google_visualr/interactive/column_chart.rb#L6)

If I want to include others packages to use on callbacks I can't, because the gem just include one package (https://github.com/winston/google_visualr/blob/master/lib/google_visualr/base_chart.rb#L77).

For example, I want the 'table' package to create a table with data details on chart click.
My workaround was load it manualy outside of the gem:
```
<script>
      google.load('visualization','1', {packages: ['corechart', 'table'], callback: Chart.init});
</script>
```

**Comment by winston** [comment]
Hmm but if you load another chart with the gem, it would `load` the appropriate package too right?

**Comment by dtelaroli** [comment]
It's not possible execute <code>load</code> twice, and the gem allows use chart just once.
My workaround outside of the gem works importing the two packages.

**Comment by winston** [comment]
Would it be possible to see some code to get a sense of your use case? Doesn't have to be actual code, but I just want to know how things are being called (especially the new chart within the callback part) Thanks!

**Comment by dtelaroli** [comment]
I did outside of gem a long time and lost de context with gem.
Thanks.

**Comment by dtelaroli** [comment]
I did outside of gem a long time and lost de context with gem.
Thanks.
